### ISSUE TITLE
Cannot find module 'consola'

### ISSUE THREAD

**Issue by Sumuyzzz** [x-extends/vxe-table#1754]
### 可复现的链接：

https://stackblitz.com/edit/vitejs-vite-qelujq?file=vite.config.ts&terminal=dev

### 问题描述与截图：

```bash
failed to load config from Project\vite.config.ts
error when starting dev server:
Error: Cannot find module 'consola'
Require stack:
- Project\node_modules\.pnpm\registry.npmmirror.com+vite-plugin-style-import@2.0.0_vite@2.9.11\node_modules\vite-plugin-style-import\dist\index.cjs
- Project\vite.config.ts
- Project\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.11_sass@1.52.3\node_modules\vite\dist\node\chunks\dep-97cb3622.js
- Project\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.11_sass@1.52.3\node_modules\vite\dist\node\cli.js
- Project\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.11_sass@1.52.3\node_modules\vite\bin\vite.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (E:\GithubProject\Visualize\demo\data_vue\node_modules\.pnpm\registry.npmmirror.com+vite-plugin-style-import@2.0.0_vite@2.9.11\node_modules\vite-plugin-style-import\dist\index.cjs:10:17)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
 ELIFECYCLE  Command failed with exit code 1. 

```

### 期望的结果：

能运行项目

### 操作系统：

win10

### 浏览器版本：

102.0.5005.63

### vue 版本：

3.2.25

### vxe-table 版本：

4.2.7-beta.0

**Comment by oseaweed** [comment]
> ### 可复现的链接：
> https://stackblitz.com/edit/vitejs-vite-qelujq?file=vite.config.ts&terminal=dev
> 
> ### 问题描述与截图：
> ```shell
> failed to load config from Project\vite.config.ts
> error when starting dev server:
> Error: Cannot find module 'consola'
> Require stack:
> - Project\node_modules\.pnpm\registry.npmmirror.com+vite-plugin-style-import@2.0.0_vite@2.9.11\node_modules\vite-plugin-style-import\dist\index.cjs
> - Project\vite.config.ts
> - Project\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.11_sass@1.52.3\node_modules\vite\dist\node\chunks\dep-97cb3622.js
> - Project\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.11_sass@1.52.3\node_modules\vite\dist\node\cli.js
> - Project\node_modules\.pnpm\registry.npmmirror.com+vite@2.9.11_sass@1.52.3\node_modules\vite\bin\vite.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (E:\GithubProject\Visualize\demo\data_vue\node_modules\.pnpm\registry.npmmirror.com+vite-plugin-style-import@2.0.0_vite@2.9.11\node_modules\vite-plugin-style-import\dist\index.cjs:10:17)
>     at Module._compile (node:internal/modules/cjs/loader:1103:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>  ELIFECYCLE  Command failed with exit code 1. 
> ```
> 
> ### 期望的结果：
> 能运行项目
> 
> ### 操作系统：
> win10
> 
> ### 浏览器版本：
> 102.0.5005.63
> 
> ### vue 版本：
> 3.2.25
> 
> ### vxe-table 版本：
> 4.2.7-beta.0

请问解决了吗我得也是

**Comment by zbs-ha** [comment]
这里有线索 [https://github.com/vbenjs/vite-plugin-style-import/issues/79](url)

**Comment by oseaweed** [comment]
> [这里有线索](https://github.com/vbenjs/vite-plugin-style-import/issues/79)

椰丝 解决了 版本升级下就好啦
